Create Radiotherapy Treatment Location and Qualifier value sets based on TG263
HL7/fhir-mCODE-ig pull request #204
Opened 2021-09-15 17:56 UTC by saulakravitz

The Radiotherapy Treatment Location and Qualifier Value sets have been reworked to align with AAPM TG263  https://www.aapm.org/pubs/reports/RPT_263.pdf.

2021-09-28 17:03 UTC, markkramerus requested changes

2021-10-01 16:02 UTC, saulakravitz commented on input/fsh/VS_Genomics.fsh
> +* SPTY#ORH      "Other"
Value set binding is already extensible, so OTHER will be removed.

2021-10-01 16:09 UTC, saulakravitz commented on input/fsh/VS_Radiotherapy.fsh
> +* SCT#55561003 "Active (qualifier value)"
Active is used to qualify 'Bone marrow structure (body structure)'.  
I don't know the difference between active and inactive.  I can find the difference between red/yellow bone marrow.
Will ask Su.

2021-10-01 20:16 UTC, saulakravitz commented on input/fsh/VS_Radiotherapy.fsh
> +* SCT#55561003 "Active (qualifier value)"
Active dropped as qualifier.
Active Bone Marrow --> Red Bone Marrow (no qualifier).

2021-10-01 20:20 UTC, saulakravitz commented on input/fsh/VS_Radiotherapy.fsh
> +* SCT#7771000    "Left (qualifier value)"
This had already been merged into master, but not into this branch.

2021-10-01 20:33 UTC, saulakravitz commented on input/fsh/VS_Radiotherapy.fsh
> +* SCT#7771000    "Left (qualifier value)"
Actually, it was fixed on master, and then messed up on this branch.   
I built the list of qualifiers form the spreadsheet, which mixed both types of qualifier.
Now fixed.

2021-10-04 13:52 UTC, markkramerus approved these changes

2021-10-04 13:52 UTC, merged