Profile conformance mk
HL7/fhir-mCODE-ig pull request #24
Opened 2020-10-14 18:29 UTC by markkramerus

Added individual conformance statements to each profile.

2020-10-15 19:56 UTC, markkramerus commented on input/fsh/CancerCondition.fsh
> +Condition resources associated with an mCODE patient with a Condition.code in the value set PrimaryOrUncertainBehaviorCancerDisorderVS MUST conform to this profile. Beyond this requirement, a produce
I did it this way: [mCODE patient](conformance.html#mCODE-Patients)

2020-10-15 20:15 UTC, markkramerus commented on input/fsh/CancerDiseaseStatus.fsh
> +Observation resources associated with an mCODE patient with Observation.code LOINC 88040-1 MUST conform to this profile. Beyond this requirement, a producer of resources SHOULD ensure that any resour
It is intentional that some resources don't have this requirement, generally those that are least mCODE-specific.

2020-10-15 20:17 UTC, markkramerus commented on input/fsh/CancerPatient.fsh
> +Patient resources representing mCODE patients (as defined in [Conformance](conformance.html#mCODE-Patients)) MUST conform to this profile. Any resource intended to conform to this profile MAY populat
OK, I was on the fence about this anyway.

2020-10-15 20:23 UTC, markkramerus commented on input/fsh/CancerRelatedMedicationStatement.fsh
> +MedicationStatement resources associated with an mCODE patient SHOULD conform to this profile. Beyond this requirement, a producer of resources SHOULD ensure that any resource instance associated wit
Medication statement is the subject of a separate PR. I would rather discuss it there.

2020-10-15 20:23 UTC, markkramerus commented on input/fsh/CancerRelatedMedicationStatement.fsh
> -* reasonCode 0..1
See my other PR. Resolved there.

2020-10-15 20:27 UTC, markkramerus commented on input/fsh/ComorbidCondition.fsh
I'm not sure what you are suggesting.

2020-10-15 20:51 UTC, markkramerus commented on input/fsh/ComorbidCondition.fsh
>  */
The ComorbidConditionParent profile provides a base profile for specific comorbidity profiles. In mCODE, one profile is defined for each comorbid condition in the Elixhauser Comorbidity Index, **with the exception of cancer conditions (the index disease in the context of mCODE).** These profiles allow implementers to tag relevant resources as conforming to their respective profiles using [`meta.profile`](https://www.hl7.org/fhir/resource-definitions.html#Meta.profile). Value sets are also defined for each comorbid condition in the Index.

2020-10-15 21:05 UTC, masnick requested changes
Just a few typo fixes, and I added to the radiation procedure statement so it parallels the surgical procedure statement.

2020-10-19 19:07 UTC, markkramerus commented on input/fsh/ComorbidCondition.fsh
> +Description:  "Elixhauser comorbid condition profile for HIV-AIDS. This profile is provided primarily so its canonical URL can be used in meta.profile to indicate a Condition instance falls into this
Fixed

2020-10-19 19:08 UTC, markkramerus commented on input/fsh/ComorbidCondition.fsh
I am not suggesting the list of comorbidities be saved.

2020-10-19 19:08 UTC, markkramerus commented on input/fsh/CancerCondition.fsh
> +Condition resources associated with an [mCODE patient](conformance.html#mCODE-Patients)with a Condition.code in the value set PrimaryOrUncertainBehaviorCancerDisorderVS MUST conform to this profile.
fixed

2020-10-19 19:10 UTC, markkramerus commented on input/fsh/CancerRelatedProcedures.fsh
> +Procedure resources associated with an [mCODE patient](conformance.html#mCODE-Patients) with Procedure.category SNOMED-CT 387713003 MAY conform to this profile. Beyond this requirement, a producer of
fixed

2020-10-19 19:11 UTC, markkramerus commented on input/fsh/CancerRelatedProcedures.fsh
> +Procedure resources associated with an [mCODE patient](conformance.html#mCODE-Patients) with Procedure.category SNOMED-CT 53438000 MAY conform to this profile. Beyond this requirement, a producer of
Added.

2020-10-19 19:19 UTC, merged