First draft for AE
HL7/fhir-mCODE-ig pull request #66
Opened 2020-12-02 22:51 UTC by markkramerus

2020-12-03 15:48 UTC, mlterryMitre requested changes
The CTCAE-relevant bindings and terms probably merit further discussion since it appears to be customized to Epic's needs (e.g.: "grade 0" for symptom free) and tight binding strength to MedDRA codes. Note that MedDRA codes are proprietary licensed through MSSO so we might need to open this up to support NCIt.

2020-12-03 15:48 UTC, mlterryMitre commented on input/fsh/SD_AdverseEvent.fsh
> +* event from MedDRAVS (required)
Make this (preferrred) since it's possible to send NCIt for CTCAE grade for NCI reporting.

2020-12-03 15:48 UTC, mlterryMitre commented on input/fsh/SD_AdverseEvent.fsh
> +* valueCodeableConcept from CTCAdverseEventGradeVS (required)
a bit too tight. NCIt is used for CTCAE grade and is in context with the CTCAE term.

2020-12-03 15:48 UTC, mlterryMitre commented on input/fsh/VS_Other.fsh
> +* SCT#162467007 "Free of symptoms (situation)"
As you know, SCT#162467007 "Free of symptoms (situation)" would be invalid for CTCAE so if we use this for reporting, it would be rejected.

2020-12-05 14:36 UTC, markkramerus commented
Working on a second draft that will be much better than this one. Closing this PR.

2020-12-05 14:36 UTC, closed without merging